### ISSUE TITLE
Can't see volume file?

### ISSUE THREAD

**Issue by devleaks** [IshtarStar/docker-compose-nginx-phpfpm-xdebug-mariadb#1]
Hello,

First of all, thank you for this handy docker compose set up.
I'm no docker specialist, and I face a problem and I tracked it down to the following: The /usr/local/etc/php/conf/666-overrides.ini is not taken into account by my setup. When I run
```
$ docker-compose run --rm php-fpm ls /usr/local/etc/php/conf.d
[+] Running 1/0
 ⠿ Container docker-compose-nginx-phpfpm-xdebug-mariadb-mariadb-1  Running                      0.0s
docker-php-ext-mysqli.ini     docker-php-ext-sodium.ini  docker-php-ext-zip.ini
docker-php-ext-pdo_mysql.ini  docker-php-ext-xdebug.ini
```
as you see, I do not see the 666-overrides.ini file.
If I do a shell on the the php-fpm image, 
I am using Docker Desktop on MacOS, engine 20.10.12, docker-compose 2.2.3.
As I said, I'm no docker specialist, how can I further track down the issue? Thank you.

PS: I added adminer to your set up, and my php app (Yii2-based) works OK except that I have to pass a few php.ini parameters and I'm stuck with the fact that the file 666-overrides.ini is not taken into account. I've found other workarounds, but I'd like to understand why I don't see that file.
Thank you for your help.

**Comment by IshtarStar** [comment]
Hello,

Thank you for pointing this out. In fact the `666-overrides.ini` was not mounted, because simply the configurations folder was not correct. This is now corrected. Instead of just `conf` it must be `conf.d`. Any ini that is mounted in the folder `/usr/local/etc/php/conf.d/` is automatically shared at runtime.

```
Configuration File (php.ini) Path => /usr/local/etc/php
Scan this dir for additional .ini files => /usr/local/etc/php/conf.d
Additional .ini files parsed => /usr/local/etc/php/conf.d/666-overrides.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini
user_ini.cache_ttl => 300 => 300
user_ini.filename => .user.ini => .user.ini
Classes => AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, CallbackFilterIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveCallbackFilterIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException
```

Thanks for the feedback.

Kind regards
Marc

**Comment by devleaks** [comment]
The typo was too difficult to spot! Thanks a lot. Best regards.
